{{- if .Values.quantumLayer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamedin-quantum.fullname" . }}-quantum-layer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gamedin-quantum.labels" . | nindent 4 }}
    component: quantum-layer
  annotations:
    {{- if .Values.quantumLayer.annotations }}
    {{- toYaml .Values.quantumLayer.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.quantumLayer.replicaCount }}
  selector:
    matchLabels:
      {{- include "gamedin-quantum.selectorLabels" . | nindent 6 }}
      component: quantum-layer
  template:
    metadata:
      labels:
        {{- include "gamedin-quantum.selectorLabels" . | nindent 8 }}
        component: quantum-layer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.quantumLayer.podAnnotations }}
        {{- toYaml .Values.quantumLayer.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gamedin-quantum.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.quantumLayer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-quantum-layer
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.quantumLayer.image.repository }}:{{ .Values.quantumLayer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.quantumLayer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.quantumLayer.service.targetPort }}
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          {{- if .Values.quantumLayer.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.quantumLayer.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.quantumLayer.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.quantumLayer.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.quantumLayer.resources | nindent 12 }}
          env:
            - name: NODE_ENV
              value: {{ .Values.quantumLayer.env.NODE_ENV | quote }}
            - name: QUANTUM_BACKEND
              value: {{ .Values.quantumLayer.env.QUANTUM_BACKEND | quote }}
            - name: QUANTUM_PROVIDER
              value: {{ .Values.quantumLayer.env.QUANTUM_PROVIDER | quote }}
            - name: QUANTUM_DEVICE
              value: {{ .Values.quantumLayer.env.QUANTUM_DEVICE | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.quantumLayer.env.LOG_LEVEL | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.quantumLayer.secrets.quantumApiKey }}
            - name: QUANTUM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.quantumLayer.secrets.quantumApiKey.secretName }}
                  key: {{ .Values.quantumLayer.secrets.quantumApiKey.secretKey }}
            {{- end }}
            {{- if .Values.quantumLayer.secrets.quantumBackendUrl }}
            - name: QUANTUM_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.quantumLayer.secrets.quantumBackendUrl.secretName }}
                  key: {{ .Values.quantumLayer.secrets.quantumBackendUrl.secretKey }}
            {{- end }}
          {{- if .Values.quantumLayer.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.quantumLayer.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.quantumLayer.envFrom }}
          envFrom:
            {{- toYaml .Values.quantumLayer.envFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.quantumLayer.command }}
          command:
            {{- toYaml .Values.quantumLayer.command | nindent 12 }}
          {{- end }}
          {{- if .Values.quantumLayer.args }}
          args:
            {{- toYaml .Values.quantumLayer.args | nindent 12 }}
          {{- end }}
          {{- if .Values.quantumLayer.lifecycle }}
          lifecycle:
            {{- toYaml .Values.quantumLayer.lifecycle | nindent 12 }}
          {{- end }}
          {{- if .Values.quantumLayer.terminationMessagePath }}
          terminationMessagePath: {{ .Values.quantumLayer.terminationMessagePath }}
          {{- end }}
          {{- if .Values.quantumLayer.terminationMessagePolicy }}
          terminationMessagePolicy: {{ .Values.quantumLayer.terminationMessagePolicy }}
          {{- end }}
          {{- if .Values.quantumLayer.securityContext }}
          securityContext:
            {{- toYaml .Values.quantumLayer.securityContext | nindent 12 }}
          {{- end }}
        {{- if .Values.quantumLayer.sidecars }}
        {{- toYaml .Values.quantumLayer.sidecars | nindent 8 }}
        {{- end }}
      {{- if .Values.quantumLayer.volumes }}
      volumes:
        {{- toYaml .Values.quantumLayer.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.initContainers }}
      initContainers:
        {{- toYaml .Values.quantumLayer.initContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.affinity }}
      affinity:
        {{- toYaml .Values.quantumLayer.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.quantumLayer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.tolerations }}
      tolerations:
        {{- toYaml .Values.quantumLayer.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.quantumLayer.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.hostNetwork }}
      hostNetwork: {{ .Values.quantumLayer.hostNetwork }}
      {{- end }}
      {{- if .Values.quantumLayer.hostPID }}
      hostPID: {{ .Values.quantumLayer.hostPID }}
      {{- end }}
      {{- if .Values.quantumLayer.hostIPC }}
      hostIPC: {{ .Values.quantumLayer.hostIPC }}
      {{- end }}
      {{- if .Values.quantumLayer.dnsPolicy }}
      dnsPolicy: {{ .Values.quantumLayer.dnsPolicy }}
      {{- end }}
      {{- if .Values.quantumLayer.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.quantumLayer.dnsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.restartPolicy }}
      restartPolicy: {{ .Values.quantumLayer.restartPolicy }}
      {{- end }}
      {{- if .Values.quantumLayer.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.quantumLayer.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.quantumLayer.automountServiceAccountToken }}
      automountServiceAccountToken: {{ .Values.quantumLayer.automountServiceAccountToken }}
      {{- end }}
      {{- if .Values.quantumLayer.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.quantumLayer.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.quantumLayer.schedulerName }}
      schedulerName: {{ .Values.quantumLayer.schedulerName }}
      {{- end }}
      {{- if .Values.quantumLayer.priorityClassName }}
      priorityClassName: {{ .Values.quantumLayer.priorityClassName }}
      {{- end }}
      {{- if .Values.quantumLayer.priority }}
      priority: {{ .Values.quantumLayer.priority }}
      {{- end }}
      {{- if .Values.quantumLayer.preemptionPolicy }}
      preemptionPolicy: {{ .Values.quantumLayer.preemptionPolicy }}
      {{- end }}
      {{- if .Values.quantumLayer.runtimeClassName }}
      runtimeClassName: {{ .Values.quantumLayer.runtimeClassName }}
      {{- end }}
      {{- if .Values.quantumLayer.enableServiceLinks }}
      enableServiceLinks: {{ .Values.quantumLayer.enableServiceLinks }}
      {{- end }}
      {{- if .Values.quantumLayer.setHostnameAsFQDN }}
      setHostnameAsFQDN: {{ .Values.quantumLayer.setHostnameAsFQDN }}
      {{- end }}
      {{- if .Values.quantumLayer.hostname }}
      hostname: {{ .Values.quantumLayer.hostname }}
      {{- end }}
      {{- if .Values.quantumLayer.subdomain }}
      subdomain: {{ .Values.quantumLayer.subdomain }}
      {{- end }}
      {{- if .Values.quantumLayer.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.quantumLayer.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.quantumLayer.readinessGates }}
      readinessGates:
        {{- toYaml .Values.quantumLayer.readinessGates | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.ephemeralContainers }}
      ephemeralContainers:
        {{- toYaml .Values.quantumLayer.ephemeralContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.os }}
      os:
        {{- toYaml .Values.quantumLayer.os | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.overhead }}
      overhead:
        {{- toYaml .Values.quantumLayer.overhead | nindent 8 }}
      {{- end }}
      {{- if .Values.quantumLayer.schedulingGates }}
      schedulingGates:
        {{- toYaml .Values.quantumLayer.schedulingGates | nindent 8 }}
      {{- end }}
{{- end }} 