{{- if and .Values.quantumLayer.autoscaling.enabled (not .Values.quantumLayer.autoscaling.external) }}
# Quantum-Detailed HPA for GameDin Quantum Layer
# This HPA automatically scales the quantum-layer deployment based on CPU and memory utilization.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gamedin-quantum.fullname" . }}-quantum-layer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gamedin-quantum.labels" . | nindent 4 }}
    component: quantum-layer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gamedin-quantum.fullname" . }}-quantum-layer
  minReplicas: {{ .Values.quantumLayer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.quantumLayer.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.quantumLayer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.quantumLayer.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }} 