{{- if .Values.security.networkPolicies.enabled }}
# Quantum-Detailed NetworkPolicy for GameDin Quantum Layer
# This policy restricts ingress and egress to only allowed sources and destinations.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gamedin-quantum.fullname" . }}-quantum-layer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gamedin-quantum.labels" . | nindent 4 }}
    component: quantum-layer
spec:
  podSelector:
    matchLabels:
      {{- include "gamedin-quantum.selectorLabels" . | nindent 6 }}
      component: quantum-layer
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.quantumLayer.service.port }}
        - protocol: TCP
          port: 9090
  egress:
    - to:
        - podSelector: {}
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }} 