apiVersion: v1
kind: Namespace
metadata:
  name: gamedin-quantum
  labels:
    name: gamedin-quantum
    purpose: quantum-computing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantum-computing
  namespace: gamedin-quantum
  labels:
    app: quantum-computing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantum-computing
  template:
    metadata:
      labels:
        app: quantum-computing
    spec:
      containers:
      - name: quantum-computing
        image: 869935067006.dkr.ecr.us-east-1.amazonaws.com/gamedin-l3/quantum-computing:5.0.0
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        - name: NODE_ENV
          value: "production"
        - name: IBM_QUANTUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantum-secrets
              key: ibm-quantum-api-key
        - name: GOOGLE_QUANTUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantum-secrets
              key: google-quantum-api-key
        - name: MICROSOFT_QUANTUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantum-secrets
              key: microsoft-quantum-api-key
        - name: AWS_BRAKET_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantum-secrets
              key: aws-braket-api-key
        - name: MIT_QUANTUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantum-secrets
              key: mit-quantum-api-key
        - name: CALTECH_QUANTUM_API_KEY
          valueFrom:
            secretKeyRef:
              name: quantum-secrets
              key: caltech-quantum-api-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: quantum-computing-service
  namespace: gamedin-quantum
  labels:
    app: quantum-computing
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: quantum-api
  selector:
    app: quantum-computing

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantum-computing-ingress
  namespace: gamedin-quantum
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:869935067006:certificate/quantum-computing"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  rules:
  - host: quantum.gamedin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quantum-computing-service
            port:
              number: 9090

---
apiVersion: v1
kind: Secret
metadata:
  name: quantum-secrets
  namespace: gamedin-quantum
type: Opaque
data:
  ibm-quantum-api-key: <base64-encoded-ibm-api-key>
  google-quantum-api-key: <base64-encoded-google-api-key>
  microsoft-quantum-api-key: <base64-encoded-microsoft-api-key>
  aws-braket-api-key: <base64-encoded-aws-api-key>
  mit-quantum-api-key: <base64-encoded-mit-api-key>
  caltech-quantum-api-key: <base64-encoded-caltech-api-key>

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quantum-computing-hpa
  namespace: gamedin-quantum
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quantum-computing
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 