apiVersion: v2
name: gamedin-quantum
description: GameDin Quantum Layer - Comprehensive quantum computing infrastructure for gaming applications
type: application
version: 4.3.2
appVersion: "4.3.2"
keywords:
  - quantum
  - gaming
  - blockchain
  - ai
  - kubernetes
  - helm
home: https://gamedin.com
sources:
  - https://github.com/gamedin/quantum-layer
  - https://github.com/gamedin/blockchain-layer
maintainers:
  - name: GameDin Team
    email: team@gamedin.com
    url: https://gamedin.com
icon: https://gamedin.com/logo.png

# Dependencies for the quantum layer
dependencies:
  # Prometheus for monitoring
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    
  # Grafana for visualization
  - name: grafana
    version: 7.0.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    
  # AlertManager for alerting
  - name: alertmanager
    version: 1.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled
    
  # Node Exporter for system metrics
  - name: node-exporter
    version: 4.35.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: nodeExporter.enabled
    
  # External Secrets Operator for secrets management
  - name: external-secrets
    version: 0.9.0
    repository: https://charts.external-secrets.io
    condition: externalSecrets.enabled
    
  # AWS Load Balancer Controller
  - name: aws-load-balancer-controller
    version: 1.7.0
    repository: https://aws.github.io/eks-charts
    condition: awsLoadBalancerController.enabled
    
  # Cluster Autoscaler
  - name: cluster-autoscaler
    version: 9.35.0
    repository: https://kubernetes.github.io/autoscaler
    condition: clusterAutoscaler.enabled
    
  # Cert Manager for SSL certificates
  - name: cert-manager
    version: v1.13.0
    repository: https://charts.jetstack.io
    condition: certManager.enabled

# Annotations for the chart
annotations:
  category: Infrastructure
  licenses: MIT
  support: GameDin Team
  keywords: "quantum,gaming,blockchain,ai,kubernetes,helm"
  description: "GameDin Quantum Layer provides comprehensive quantum computing infrastructure for gaming applications including entanglement synchronization, AI decision trees, quantum randomness, and game optimization." 