name: codexmeta

on:
  push:
    paths:
      - '.codexmeta'
      - 'codexmeta.schema.json'
      - '.github/workflows/codexmeta-validation.yml'
      - 'scripts/validate-codexmeta.js'
  pull_request:
    paths:
      - '.codexmeta'
      - 'codexmeta.schema.json'
      - '.github/workflows/codexmeta-validation.yml'
      - 'scripts/validate-codexmeta.js'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate covenant metadata
        run: node scripts/validate-codexmeta.js
