name: Workflow Hygiene

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          level: error

  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          level: error

  dependabot:
    name: Check Dependabot configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Dependabot configuration
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.github/dependabot.yml';
            
            if (fs.existsSync(path)) {
              console.log('Dependabot configuration found and is valid');
            } else {
              console.warn('No Dependabot configuration found. Consider adding one to keep dependencies up to date.');
              // This is a warning, not an error
              // core.setFailed('Dependabot configuration is missing');
            }

  required-labels:
    name: Check for required labels
    runs-on: ubuntu-latest
    steps:
      - name: Check for required labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data: labels } = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            const requiredLabels = [
              'bug',
              'enhancement',
              'documentation',
              'dependencies',
              'question',
              'wontfix'
            ];
            
            const missingLabels = requiredLabels.filter(
              label => !labels.some(l => l.name.toLowerCase() === label)
            );
            
            if (missingLabels.length > 0) {
              console.warn(`The following labels are recommended but missing: ${missingLabels.join(', ')}`);
              // This is a warning, not an error
              // core.setFailed('Missing recommended labels');
            }
